### PR TITLE
Bluetooth Restoration bug fix

### PR DESCRIPTION
**Pull request by Soulphalanx**
Fixes a case where Bluetooth restoration would fail if no scanning options were specified for that central. Setting the CentralManager's options property from the options in willRestoreState was removed because the options given in that method pertains to `CBCentralManagerRestoredStateScanOptionsKey` and not CBCentralManager options. The parameter names have been modified to reflect this.

### CODE REVIEW

**Comment by troystribling** [comment]
Thanks finding this bug. One of the test cases is failing. Could you fix it? To run the test cases run `pod install`in the Tests folder and open the generated workspace. Also, `scanOptions` could be removed from the interface. If this is done options could also be removed as a property but I will take care of that later.

**Comment by Soulphalanx** [comment]
I've updated the test and it's now passing. I've left scanOptions in the interface as there's still the restoration of a scan if the app was terminated while performing one. I don't have time right now, but I will probably eventually update it, especially if I end up needing it.

**Comment by troystribling** [comment]
Sounds good when tests pass will merge.

**Comment by Soulphalanx** [comment]
Weird, it doesn't seem to be building.

**Pull request merged**
