### PR TITLE
Added some threading to fix the library crash problems.

### PR DESCRIPTION
**Pull request by hockeybro12**
I added some threading and some other checks to make sure that the app doesn't crash when starting up this library.

### CODE REVIEW

**Comment by troystribling** [comment]
I merged the PR to this branch https://github.com/troystribling/BlueCap/tree/hockeybro12-master. The tests are deadlocking on `PeripheralManager#add_services`. I am closing this PR. If you want to updated branch from the PR branch.

**Comment by hockeybro12** [comment]
How do I run the tests again, to make sure it works?

**Comment by troystribling** [comment]
Go to this directory https://github.com/troystribling/BlueCap/tree/master/Tests, run pod install. Open the BlueCapKitTests workspace and run the tests from the tests tab.

**Comment by troystribling** [comment]
To fix the problem service discovery may need to be rewritten. There is a recursive call causing the deadlock. For now this can be removed. I can take a look later. The other changes look OK.

**Comment by hockeybro12** [comment]
Ok, so I guess I don't need to fix anything anymore then?

**Comment by troystribling** [comment]
I will take care of it.

**Pull request closed without merging**
