### PR TITLE
Revert " More Swift 2.2 deprecations"

### PR DESCRIPTION
**Pull request by troystribling**
Reverts troystribling/BlueCap#26. This did not build with Xcode 7.2.1

### CODE REVIEW

**Comment by troystribling** [comment]
Are you using Xcode 7.3 beta 5? If so I will make a new branch and do merge there.

**Comment by cbowns** [comment]
Yeah, sorry about that, I hit the same issue in our codebase but didn't update the PR.

**Comment by troystribling** [comment]
I added a swift-3 branch. Will merge there. It should be used for future swift 3 changes.

**Comment by cbowns** [comment]
:+1: great!

**Pull request closed without merging**
